version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=family-tree
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306    
  app:
    restart: on-failure
    depends_on:
      - mysqldb
    build: .
    ports:
      - 8080:8080  
    environment:      
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/family-tree",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "password",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

